import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ghelisyah = localFont({
  src: "./fonts/Ghelisyahfreeversion-Regular.ttf",
  variable: "--font-ghelisyah",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${ghelisyah.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
